# Generated by Django 3.1.7 on 2021-09-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmodel',
            name='cat_breed',
            field=models.CharField(choices=[('Billy', 'Billy'), ('Persian Cats', 'Persian Cats'), ('American Curl Cats', 'American Curl Cats'), ('Mumbai Cats', 'Mumbai Cats'), ('Munchkin Cats', 'Munchkin Cats')], max_length=50),
        ),
    ]
